### ISSUE TITLE
Intégrer les snippets

### ISSUE THREAD

**Issue by gauthierna** [numerique-gouv/content-manager#17]
Permet d'utiliser des "modules" réutilisables à plusieurs endroits dans le site, on modifie à un endroit et ça change partout.

Hyper pratique pour des blocs "Call to action" qui sont les mêmes sur plusieurs pages/landing !

[Cf la doc ici](https://guide.wagtail.org/en-latest/how-to-guides/manage-snippets/)

**Comment by Ash-Crow** [comment]
Bonjour, je ne suis pas sûr de ce qui est demandé ici (on ne peut pas juste activer "les snippets" de manière générale, il faut créer un ou plusieurs snippets particuliers. Je clos cette tâche mais n'hésitez pas à réouvrir des tâches s'il y a des snippets particuliers à créer.
