### ISSUE TITLE
Le bouton dans le bloc promotionnel n'apparait pas

### ISSUE THREAD

**Issue by Fantine-py** [numerique-gouv/content-manager#23]
Quand j'ajoute le bloc promotionnel, bien que je remplisse les infos concernant le bouton, il n'apparaît pas

**Comment by SebastienReuiller** [comment]
Bonjour @Fantine-py , est-t-il possible d'avoir une capture d'écran des infos complétées ? Parfois, c'est un autre bloc de la page pour lequel il manque des champs et cela empêche la prévisualisation.

**Comment by Ash-Crow** [comment]
Bonjour @Fantine-py , le problème est-il toujours présent ? Si oui, est-il possible d’avoir les infos demandées par Sébastien ?

**Comment by Ash-Crow** [comment]
Bonjour, en l'absence de réponse, je me permets de clore l'issue.

**Comment by Fantine-py** [comment]
Bonjour,

Désolée j'étais en formation et absente ces dernières semaines !

Bonne journée,
Fantine
*Fantine Monot*
Atelier numérique du ministère de la Culture | beta.gouv.*fr*
06 32 32 89 82
***@***.***


Le mer. 6 déc. 2023 à 15:41, Sylvain Boissel ***@***.***> a
écrit :
