### ISSUE TITLE
Pouvoir modifier le pied de page DSFR depuis l'admin de Wagtail

### ISSUE THREAD

**Issue by mjeammet** [numerique-gouv/content-manager#40]
# Objectif

J'aimerais pouvoir apporter des modifications au footer (notamment pour y mettre les bonnes urls d'accessibilité, mentions légales, etc) depuis l'interface admin de wagtail.

**Comment by JoelCha** [comment]
Bonjour,

Même demande !

**Comment by mjeammet** [comment]
Hello ! Après discussion avec Sébastien, les urls du pied de page peuvent être modifiées en allant dans l'admin puis : 
- naviguer jusqu'à paramètres > menu additionnel 
- créer un menu 
- y ajouter des éléments, pointant vers les pages souhaitées (préalablement crées, avec la mention "Faire apparaître dans les menus" cochée)

Les liens devraient apparaitre en bas de page 🎉 . 

Pour les descriptions, pour l'instant il faut encore modifier le fichier title.json ajouté au déploiement. 

On va essayer de documenter tout ça.

**Comment by Ash-Crow** [comment]
La description est maintenant éditable depuis l'admin.

Ok pour la fermeture ?
