### ISSUE TITLE
PB dark theme

### ISSUE THREAD

**Issue by revolunet** [numerique-gouv/content-manager#76]
Quand on a le dark theme par défaut, petit souci sur page d'accueil

<img width="1305" alt="Capture d’écran 2024-01-09 à 15 04 33" src="https://github.com/numerique-gouv/content-manager/assets/124937/03411e56-0513-42cf-9f65-4f41d57ed642">

**Comment by Ash-Crow** [comment]
Résolu par la mise à jour en 1.3.
