### ISSUE TITLE
Documentation démarrage

### ISSUE THREAD

**Issue by cdugeai** [numerique-gouv/content-manager#8]
Une fois le projet lancé via docker, on a bien accès à la page sur http://localhost:8000 .

J'ai ensuite suivi la doc de https://github.com/wagtail/bakerydemo#setup-with-docker qui indique de se rendre sur http://localhost:8000/admin .

Or je n'ai rien sur cette page (cf capture):

![image](https://user-images.githubusercontent.com/46027833/219005477-3a42adac-6bb5-4213-96c6-7e48bd09c2f9.png)

Est-ce qu'il y a un processus de démarrage que je n'ai pas suivi ?

Merci !

**Comment by cdugeai** [comment]
Pas du tout, je n'ai rien pu faire depuis :face_with_spiral_eyes:

**Comment by fabienheureux** [comment]
Je pense qu'il faut exécuter les migrations, qui vont créer une homepage :
```sh
docker compose run web python manage.py migrate
```

**Comment by fabienheureux** [comment]
J'ai lu trop vite, en regardant le code l'admin est exposée sur `cms-admin` et non `admin`. 
Donc l'admin doit être accessible sur http://localhost:8000/cms-admin

**Comment by cdugeai** [comment]
Je me retrouve avec cette page, est-ce normal ?

![image](https://github.com/betagouv/content-manager/assets/46027833/d95029fa-a1d6-402a-9328-53fdacf2a1ca)

**Comment by fabienheureux** [comment]
Ça ressemble à des fichiers statiques manquants 

```
docker compose run web python manage.py collectstatic
```

**Comment by cdugeai** [comment]
Merci, j'essaye ça ! Ces commandes à faire tourner se trouvent où ? Dans la doc Wagtail ?

**Comment by fabienheureux** [comment]
Pour `collectstatic`, c'est une commande qui vient de django, je ne pense pas qu'elle soit tellement documentée dans Wagtail. L'écosystème wagtail présume que les développeurs connaissent django, mais c'est de moins en moins le cas. 
  
Cela dit, en local en principe elle n'a pas à être lancée, car dans le cas présent elle est lancée dans la compilation de l'image Docker https://github.com/betagouv/content-manager/blob/main/Dockerfile#L28. 
Ça a résolu le problème chez toi ?

**Comment by Ash-Crow** [comment]
Bonjour, les deux commandes nécessaires sont maintenant gérées par le `make init` présent dans la documentation de démarrage, je pense qu'on peut donc fermer cette tâche.
