### ISSUE TITLE
Bug: la page d'admin de gestion des menus additionnels ne fonctionne plus

### ISSUE THREAD

**Issue by SebastienReuiller** [numerique-gouv/content-manager#91]
Lorsqu'on souhaite accéder à la gestion des menus additionnels ici :

![image](https://github.com/numerique-gouv/content-manager/assets/17601807/cf95dc52-652d-48ac-bf83-fab8063dae39)

Nous avons désormais l'erreur :

```
TemplateSyntaxError at /cms-admin/wagtailmenus/flatmenu/
Invalid block tag on line 5: 'field', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
```

![screenshot-localhost_8000-2024 03 04-15_49_08](https://github.com/numerique-gouv/content-manager/assets/17601807/9305b0a7-6ced-4da0-b9e5-e6ff8f22c453)

**Comment by Ash-Crow** [comment]
Vu le message d'erreur, le bug a l'air d'être dans wagtail_modeladmin

**Comment by Ash-Crow** [comment]
Hmm, j'ai essayé d'installer un wagtail minimaliste avec juste wagtailmenus en plus et tout a l'air de marcher.

Je n'arrive pas à trouver l'origine du problème.

**Comment by Ash-Crow** [comment]
Après avoir repassé les mises à jour de février une par une, c'est ce commit qui a pété le menu : https://github.com/numerique-gouv/content-manager/commit/6d7f30ef89078f7d708944b7f12ec67d5e4df57a

**Comment by SebastienReuiller** [comment]
Super, merci @Ash-Crow pour la correction ! 🙏
